MODULES = blmfl
EXTENSION = blmfl # the extension's name
DATA = blmfl--0.0.1.sql	# script file to install
# REGRESS = blmfl_test  	# the test script file

PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)

include $(PGXS)