version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - type: bind
        source: ./shared/
        target: /shared/
    ports:
      - "5432:5432"
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file: ./secrets/pgadmin.env
    environment:
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "postgres:postgres-server"

volumes:
  postgres-data:
  pgadmin-data:

secrets:
  POSTGRES_USER:
    file: ./secrets/POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD
